config/routes.rb
	Rails.application.routes.draw do
  devise_for :users, path: "", path_name: {sign_in: "login", sign_out: "logout"}
  
  resources :users
  
  resources :products do
  	resources :comments
  end
  
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'static_pages#landing_page'

  get 'static_pages/about', path: 'about'
  get 'static_pages/contact', path: 'contact'

  post 'static_pages/thank_you'

  post 'payments/create'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  	user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

	validates :name, presence: true

	def average_rating
		comments.average(:rating).to_f
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to main_app.root_url, :alert => exception.message
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	  @product = Product.find(params[:product_id])
	  @comment = @product.comments.new(comment_params)
	  @comment.user = current_user
	  respond_to do |format|
	  	if @comment.save
	  		format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
      	format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy
		redirect_to product
	end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :body, :rating)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?
  respond_to :json, :html
  
  before_filter :authenticate_user!
  
  def index
    @orders = Order.all.to_json(include: [{product: {only: :name}}, {user: {only: :email}}])
    respond_with @orders
  end

  def show
    @order - Order.find(params[:id]).to_json(include: [{product: {only: :name}}, {user: {only: :email}}])
    respond_with @orders
  end

  def new
  end

  def create
    @order = Order.create(order_params)
    respond_with @order
  end

  def destroy
    respond_with Order.destroy(params[:id])
  end
  
  protected
  
  def json_request?
    request.format.json?
  end
  
  private
  
  def order_params
    params.require(:order).permit(:product_id, :user_id, :total)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def create
		token = params[:stripeToken]
		@product = Product.find(params[:product_id])
		@user = current_user

		begin
			charge = Stripe::Charge.create(
				amount: (@product.price*100).to_i,
				currency: "gbp",
				source: token,
				description: params[:stripeEmail]
			)

			if charge.paid
				Order.create(
					product_id: @product.id,
					user_id: @user.id,
					total: @product.price
				)
			end

    flash[:success] = "Your payment was processed successfully"

		rescue Stripe::CardError => e
			body = e.json_body
			err = body[:error]
			flash[:error] = "Unfortunately, there was an error processing your payment: #{err[:message]}"
		end
	
		redirect_to product_path(@product)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  respond_to :json, :html

  def index
  if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
  else
    @products = Product.all
  end
  respond_with @products
end

  def show
    @comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.paginate(page: params[:page], per_page: 5)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :color, :image_url, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  
  def landing_page
    @products = Product.limit(3)
  end

  def contact
  end

  def thank_you
	  @name = params[:name]
	  @email = params[:email]
	  @message = params[:message]
	  UserMailer.contact_form(@email, @name, @message).deliver_now
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
  <hr>
  <p>
  	<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
  	<% if signed_in? && current_user.admin? %>
    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are u sure?'}  %>
   <% end %>
  </p>
  <p><%= "Rating: #{comment.rating}/5" %></p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>

app/views/comments/create.js.erb
$("#new_comment").html("We thank you for this review");

$(".product-reviews").pretend("<%= j render @comment %>");

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Berlin Bikes', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', static_pages_about_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Orders', orders_path %></li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
          <% else %>
            <%= link_to("Login", new_user_session_path) %>
          <% end %>
        </li>
      </ul>
        <%= form_tag("/products", method:"GET", class: "navbar-form navbar-right") do %>
        <div class="form-group">
          <%= label_tag(:q, "Search for:", class: "hidden") %>
          <%= text_field_tag(:q, "", placeholder: "Search", class: "form-control") %>
          <%= submit_tag("Submit") %>
        </div>
        <% end %>


      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Berlin Bikes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

	<% if notice %>
    <p class="alert alert-info"><%= notice %></p>
   <% else %>
   	<p class="alert alert-info"><%= alert %></p>
	<% end %>
	
  <%= render 'layouts/navigation' %>

	<div class="container-fluid">
	  <%= yield %>
	</div>

	<footer>
	  <p>&copy; Berlin Bikes. 2016 All Rights Reserved.</p>
	</footer>

</body>
</html>

app/views/orders/index.html.erb
<div ng-controller="OrdersCtrl">

	<form class="form-inline" ng-submit="addOrder()">
		<strong>Add Order: </strong>

		<select ng-model="newOrder.product_id" class="form-control">
			<option value="" disabled selected>Select a product</option>
			<option value="{{ product.id }}" ng-repeat="product in products">{{ product.name }}</option>
		</select>
		
		<input type="number" step="0.01" class="form-control" placeholder="Total" ng-model="newOrder.total">
		<input type="number" class="form-control" ng-model="newOrder.product_id">

		<input type="submit" value="+" class="btn btn-success">
	</form>
	
	<h2>Orders</h2>

	<input type="text" placeholder="Your Name" ng-model="name" >

	<table class="table table-hover">
		<thead>
			<td>Order ID</td>
			<td>Total</td>
			<td>Product</td>
			<td></td>
		</thead>

		<tr ng-repeat="order in orders | orderBy:'-id':reverse">
			<td>
				{{ order.id }}
			</td>
			<td>
				<strong>{{ order.total | currency }}</strong>
			</td>
			<td>
				{{ order.product.name }}
				<small ng-show="order.user_id"><br>Ordered by: {{ order.user.email }}</small>
			</td>
			<td>
	      {{order.created_at}}
      </td>
			<td>
				<button ng-click="deleteOrder(order)" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
			</td>
		</tr>
	</table>

</div>

app/views/payments/create.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you for your purchase.  Great choice!</p>
    <p><%= link_to "Back to Products", products_path %></p>
  </div>
</div>

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p>
      	<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
      	<% if signed_in? && current_user.admin? %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are u sure?'}  %>
       <% end %>
      </p>
      <p><%= "Rating: #{comment.rating}/5" %></p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
      </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<div class="wrapper">
  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, step: "any", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>

    <p>
     <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<%= image_tag(product.image_url, class: "img-responsive")%>
<h4 class="heading"><%= link_to product.name, product %></h4>
<!-- <%= product.description %> -->
</div>
<!-- <%= link_to 'Show', product %>
<%= link_to 'Edit', edit_product_path(product) %>
<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> -->

app/views/products/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/square-image.png"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= @product.price*100 %>">
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="title">Recent Products</h1>

  <div class="row">
    <% @products.each do |product| %>
      <%= render partial: "product", locals: {product: product} %>
    <% end %>
</div>
  
  <br>

  <div id="title"><%= link_to 'New Product', new_product_path %></div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="content">
	<h4 class="title"><%= @product.name %></h4>
	<p class="description"><%= @product.description %></p>
	
	<strong>Price</strong>
	<p class="price">$<%= @product.price %></p>

	<strong>Colour</strong>
	<p class="color"><%= @product.color %></p>

	<div class="image"><%= image_tag(@product.image_url, class: "img-responsive img-zoom", data_zoom_image: "@product.image_url") %></div>

	<%= form_tag "/payments/create" do %>
		<%= render "stripe_checkout_button" %>
		<%= hidden_field_tag(:product_id, @product.id) %>
	<% end %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to "Delete Product", product_path(@product), method: :delete, data: { confirm: "Are you sure?" } %>

<%= render 'new_comment' %>
<%= render 'comments' %>

<%= will_paginate @comments %>

<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>

<%= form_tag("/static_pages/thank_you") do %>
<div class="row">
  <div class="col-md-4">
    <div class="form-group">
      <%= label_tag :name, "Name" %>
      <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
    </div>      
    <div class="form-group">
      <%= label_tag :email, "Email Address" %>
      <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
    </div>
    <div class="form-group">
      <%= label_tag :message, "Message" %>
      <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
    </div>      
  </div>
</div>
<%= submit_tag "Send", class: "btn btn-primary" %>   
<% end %>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <%= image_tag("racebike.png", class: "img-responsive") %>
  <h1>Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  </p>
</div>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
		<% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
			<%= image_tag(product.image_url) %>
      <div class="carousel-caption">
        <h3><%= product.name %></h3>
      </div>
    </div>
		<% end %>
  </div>
	
  <%= params[:example_key] %>
  
	<!-- Controls -->
 <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	 <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	 <span class="sr-only">Previous</span>
 </a>
 <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	 <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	 <span class="sr-only">Next</span>
 </a>
</div>

app/views/static_pages/thank_you.html.erb
<div class="text-center">
	<h2>Thank you for your email</h2>
	<p>We shall get back to you shortly!</p>

	<%= link_to "Go Home", root_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>